services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tokenization-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_strong_password123"
    ports:
      - "14333:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"Your_strong_password123\" -Q \"SELECT 1\" -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: tokenization-redis
    ports:
      - "6379:6379"
